#!/usr/bin/env bash

CLAUDE_REVIEW_MAX_ARTIFACT_BYTES="${CLAUDE_REVIEW_MAX_ARTIFACT_BYTES:-200000}"
CLAUDE_REVIEW_MAX_SPLIT_PARTS="${CLAUDE_REVIEW_MAX_SPLIT_PARTS:-12}"
CLAUDE_REVIEW_MAX_ARTIFACT_BYTES_INPUT="$CLAUDE_REVIEW_MAX_ARTIFACT_BYTES"
CLAUDE_REVIEW_MAX_SPLIT_PARTS_INPUT="$CLAUDE_REVIEW_MAX_SPLIT_PARTS"

artifact_limits_abort() {
  printf 'Invalid %s: %s\n' "$1" "$2" >&2
  if [ "${BASH_SOURCE[0]}" != "$0" ]; then
    return 2
  fi
  exit 2
}

case "$CLAUDE_REVIEW_MAX_ARTIFACT_BYTES" in
  ''|*[!0-9]*|0)
    artifact_limits_abort "CLAUDE_REVIEW_MAX_ARTIFACT_BYTES" "$CLAUDE_REVIEW_MAX_ARTIFACT_BYTES" || return $?
    ;;
esac

case "$CLAUDE_REVIEW_MAX_SPLIT_PARTS" in
  ''|*[!0-9]*|0)
    artifact_limits_abort "CLAUDE_REVIEW_MAX_SPLIT_PARTS" "$CLAUDE_REVIEW_MAX_SPLIT_PARTS" || return $?
    ;;
esac

CLAUDE_REVIEW_MAX_ARTIFACT_BYTES="$((10#$CLAUDE_REVIEW_MAX_ARTIFACT_BYTES))"
if [ "$CLAUDE_REVIEW_MAX_ARTIFACT_BYTES" -le 0 ]; then
  artifact_limits_abort "CLAUDE_REVIEW_MAX_ARTIFACT_BYTES" "$CLAUDE_REVIEW_MAX_ARTIFACT_BYTES_INPUT" || return $?
fi

CLAUDE_REVIEW_MAX_SPLIT_PARTS="$((10#$CLAUDE_REVIEW_MAX_SPLIT_PARTS))"
if [ "$CLAUDE_REVIEW_MAX_SPLIT_PARTS" -le 0 ]; then
  artifact_limits_abort "CLAUDE_REVIEW_MAX_SPLIT_PARTS" "$CLAUDE_REVIEW_MAX_SPLIT_PARTS_INPUT" || return $?
fi
